server:
  port: 7071
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB
  application:
    name: gem_fan_club_web
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: update
        jdbc:
          time_zone: GMT+8
          batch_size: 20
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: false
        order_inserts: true
        order_updates: true
    show-sql: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/gem_fan_club?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: HikariCPDatasource
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  data:
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      timeout: 2000
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 5
          max-wait: 1000ms
project:
  root: ${user.dir}  # 获取当前项目的根目录
file:
  upload-dir: ${project.root}/asserts

ai:
  service:
    url: http://localhost:8000/chat_gem

# 雪花算法配置
snowflake:
  worker-id: -1  # -1表示自动使用IP地址最后一段，也可以指定0-31的数字
  data-center-id: 0
